_target_: schnetpack.representation.FieldSchNet
n_atom_basis: 128
n_interactions: 5
external_fields: []
response_properties: ${response_properties}
shared_interactions: False
#shared_filters: False
radial_basis:
  _target_: schnetpack.nn.radial.GaussianRBF
  n_rbf: ${n_rbf}
  cutoff: ${cutoff}
cutoff_fn:
  _target_: schnetpack.nn.cutoff.CosineCutoff
  cutoff: ${cutoff}