defaults:
  - radial_basis: gaussian

_target_: schnetpack.representation.PaiNN
n_atom_basis: 128
n_interactions: 3
shared_interactions: False
shared_filters: False
cutoff_fn:
  _target_: schnetpack.nn.cutoff.CosineCutoff
  cutoff: ${globals.cutoff}