defaults:
  - radial_basis: gaussian

_target_: schnetpack.representation.SO3net
_recursive_: False
n_atom_basis: 64
n_interactions: 3
lmax: 2
shared_interactions: False
cutoff_fn:
  _target_: schnetpack.nn.cutoff.CosineCutoff
  cutoff: ${globals.cutoff}