_target_: pytorch_lightning.Trainer

devices: 1

min_epochs: null
max_epochs: 100000

# prints
enable_model_summary: True
profiler: null

gradient_clip_val: 0
accumulate_grad_batches: 1
val_check_interval: 1.0
check_val_every_n_epoch: 1

num_sanity_val_steps: 0
fast_dev_run: False
overfit_batches: 0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
detect_anomaly: False

precision: 32
accelerator: auto
num_nodes: 1
deterministic: False
inference_mode: False
