defaults:
  - representation: painn

_target_: schnetpack.atomistic.AtomisticModel

optimizer_cls: torch.optim.AdamW
optimizer_args:
  lr: ${lr}
  amsgrad: False
  weight_decay: 0.0

scheduler_cls: schnetpack.train.ReduceLROnPlateau
scheduler_monitor: val_loss
scheduler_args:
  mode: min
  factor: 0.5
  patience: 50
  min_lr: 1e-6
  smoothing_factor: 0.3

output_modules: ???
outputs: ???
