defaults:
  - base_model

output_modules:
  - _target_: schnetpack.atomistic.Atomwise
    output: ${property}
    n_in: ${model.representation.n_atom_basis}
    aggregation_mode: sum
    module_dim: True

outputs:
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${property}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 1
