# @package _global_

defaults:
  - train_base
  - override /model: single_property
  - override /data: qm9

cutoff: 5.0
n_rbf: 20
lr: 5e-4

property: energy_U0
name: qm9_${property}

data:
  distance_unit: Ang
  property_units:
    energy_U0: eV
  transforms:
    - _target_: schnetpack.transform.SubtractCenterOfMass
    - _target_: schnetpack.transform.RemoveOffsets
      property: ${property}
      remove_atomrefs: True
      remove_mean: True
    - _target_: schnetpack.transform.CachedNeighborList
      cache_path: ${work_dir}/cache
      keep_cache: False
      neighbor_list:
        _target_: schnetpack.transform.ASENeighborList
        cutoff: ${cutoff}
    - _target_: schnetpack.transform.CastTo32

model:
  postprocess:
    - _target_: schnetpack.transform.CastTo64
    - _target_: schnetpack.transform.AddOffsets
      property: ${property}
      add_mean: True
      add_atomrefs: True