# @package _global_

defaults:
  - train
  - override /model: single_property
  - override /data: materials_project

cutoff: 5.0
n_rbf: 20
lr: 1e-3

property: formation_energy_per_atom
run_dir: runs/mp_${property}

data:
  distance_unit: Ang
  property_units:
    energy: eV
  transforms:
    - _target_: schnetpack.transform.SubtractCenterOfMass
    - _target_: schnetpack.transform.RemoveOffsets
      property: ${property}
      remove_atomrefs: True
      remove_mean: True
    - _target_: schnetpack.transform.ASENeighborList
      cutoff: ${cutoff}
    - _target_: schnetpack.transform.CastTo32

model:
  postprocess:
    - _target_: schnetpack.transform.CastTo64
    - _target_: schnetpack.transform.AddOffsets
      property: ${property}
      add_mean: True
      add_atomrefs: True